In [49]:
import numpy as np
import pandas as pd
import functions as funs
import model as mod
import matplotlib.pyplot as plt

myData = funs.dataObject()

In [41]:
def loglike(params, dataObject, covType, z = 'NaN', cov = 0):
    #check for valid covType 
    if covType == 'sys':
        cov = dataObject.covStat
    elif covType == 'tot':
        cov = dataObject.covTotal
    elif covType == int:
        cov = cov
        print('cov set to int value', cov)
    else:
        raise TypeError('covType must = "sys" or "tot"')
    
    #set redshift
    if z == 'NaN':
        z = dataObject.zcmb
    else:
        z == z
    
    #set model 
    m = mod.model(z, params)
    
    covInv = np.linalg.inv(cov)
    
    deltaM = z - m
    
    #This will break right now for single z value
    chi2 = deltaM @ covInv @ deltaM
    
    return(-chi2/2)

In [39]:
params = np.array([1000,.1,.1,.1])
z = 1
mod.model(1, params)

38.332827335406996

In [42]:
loglike(params, myData, 'sys')

-846745.7176547664

In [25]:
myData?


In [26]:
mod.model?

In [6]:
myData.covSys

array([[4.550000e-04, 2.604450e-04, 2.728900e-04, ..., 1.010500e-05,
        7.052000e-05, 2.991250e-04],
       [2.604450e-04, 7.944400e-04, 1.326800e-04, ..., 8.776500e-05,
        1.174200e-04, 2.373850e-04],
       [2.728900e-04, 1.326800e-04, 2.166850e-04, ..., 1.490000e-06,
        1.019800e-04, 3.108300e-04],
       ...,
       [1.010500e-05, 8.776500e-05, 1.490000e-06, ..., 6.024750e-04,
        7.305850e-04, 8.186400e-04],
       [7.052000e-05, 1.174200e-04, 1.019800e-04, ..., 7.305850e-04,
        2.527705e-03, 2.599130e-03],
       [2.991250e-04, 2.373850e-04, 3.108300e-04, ..., 8.186400e-04,
        2.599130e-03, 3.628650e-03]])

In [24]:
myData.covStat @  myData.mb

array([0.4531276 , 0.40277955, 0.36807776, 0.3859119 , 0.47899612,
       0.57563711, 0.56506345, 0.78626895, 0.70257999, 0.78392279,
       0.67976882, 0.66921467, 0.64322122, 0.50364937, 0.51528749,
       0.46276415, 0.47268471, 0.51866096, 0.3996594 , 0.45212964,
       0.44266758, 0.48606205, 0.46735094, 0.42937681, 0.47213586,
       0.46610643, 0.46680413, 0.51401786, 0.47496508, 0.7217524 ,
       0.57297135, 0.669103  , 0.61758113, 0.57086065, 0.72861247,
       0.64439899, 0.60126489, 0.68009525, 1.42588006, 1.90555901])

In [21]:
myData.covStat

array([[0.0311 , 0.     , 0.     , ..., 0.     , 0.     , 0.     ],
       [0.     , 0.02645, 0.     , ..., 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.0231 , ..., 0.     , 0.     , 0.     ],
       ...,
       [0.     , 0.     , 0.     , ..., 0.0276 , 0.     , 0.     ],
       [0.     , 0.     , 0.     , ..., 0.     , 0.05635, 0.     ],
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.0735 ]])

In [22]:
myData.mb

array([14.57001926, 15.22796035, 15.93410232, 16.42178296, 16.83641896,
       17.23464399, 17.57584596, 17.91045435, 18.17800746, 18.55438558,
       18.7006554 , 19.03882424, 19.17201854, 19.37112952, 19.55550262,
       19.81859308, 19.94450252, 20.06425376, 20.33890089, 20.50474561,
       20.6854008 , 20.86103225, 21.05184401, 21.20379307, 21.36361378,
       21.57900143, 21.81327728, 21.9665751 , 22.14289401, 22.37991924,
       22.55792725, 22.79737664, 23.00115944, 23.3004345 , 23.50362803,
       23.8666293 , 24.24455198, 24.64113237, 25.30399402, 25.92597291])

In [28]:
myData.mb @ myData.covStat @  myData.mb

509.8141107800783

In [54]:
loglikelist = []
for i in range(10000):
    params = np.random.rand(4)
    loglikelist.append(loglike(params, myData, 'sys'))
print(4)
#plt.hist(loglikelist)

4
